python supply_chain_model.py

# -*- coding: utf-8 -*-
"""supply_chain_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fobNqsvbybtpBcj2dnBKL2isWcjLi_87
"""

import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import cvxpy as cp
from matplotlib.patches import FancyBboxPatch

def solve_transportation_problem():
    """Solve the transportation problem (same as before)"""
    # Data
    factories = ["F1", "F2"]
    customers = ["C1", "C2", "C3"]
    capacity = np.array([100, 80])
    demand = np.array([50, 70, 40])
    cost = np.array([[4, 6, 9], [5, 4, 7]])

    # Model
    x = cp.Variable((len(factories), len(customers)), nonneg=True)
    objective = cp.Minimize(cp.sum(cp.multiply(cost, x)))
    constraints = [
        cp.sum(x, axis=1) <= capacity,
        cp.sum(x, axis=0) == demand
    ]

    problem = cp.Problem(objective, constraints)
    problem.solve()

    return factories, customers, x.value, capacity, demand, problem.value

def create_transportation_network(flows, costs=None):
    """
    Create a network graph from transportation flows

    Parameters:
    flows: 2D array of shipment quantities
    costs: 2D array of transportation costs (optional)
    """
    G = nx.DiGraph()

    # Add nodes with attributes
    factories = ["F1", "F2"]
    customers = ["C1", "C2", "C3"]

    for f in factories:
        G.add_node(f, type='factory', layer=0)

    for c in customers:
        G.add_node(c, type='customer', layer=1)

    # Add edges with weights and costs
    for i, f in enumerate(factories):
        for j, c in enumerate(customers):
            if flows[i, j] > 0.01:  # Only show positive flows
                G.add_edge(f, c,
                          weight=flows[i, j],
                          cost=costs[i, j] if costs is not None else None)

    return G, factories, customers

def visualize_transportation_network(G, factories, customers,
                                    capacity=None, demand=None,
                                    total_cost=None):
    """
    Enhanced visualization of transportation network
    """
    fig, ax = plt.subplots(figsize=(12, 8))

    # Create hierarchical layout
    pos = {}
    # Position factories on left (x=0) with vertical spacing
    for i, f in enumerate(factories):
        pos[f] = (0, 1 - i/(len(factories)-1) if len(factories)>1 else 0.5)
    # Position customers on right (x=1) with vertical spacing
    for i, c in enumerate(customers):
        pos[c] = (1, 1 - i/(len(customers)-1) if len(customers)>1 else 0.5)

    # Draw nodes with different styles based on type
    factory_nodes = [n for n in G.nodes() if n in factories]
    customer_nodes = [n for n in G.nodes() if n in customers]

    # Draw factory nodes
    nx.draw_networkx_nodes(G, pos, nodelist=factory_nodes,
                          node_color='lightblue', node_size=2000,
                          node_shape='s', ax=ax)

    # Draw customer nodes
    nx.draw_networkx_nodes(G, pos, nodelist=customer_nodes,
                          node_color='lightgreen', node_size=2000,
                          node_shape='o', ax=ax)

    # Draw edges with varying thickness based on flow
    edges = G.edges(data=True)
    widths = [data['weight']/10 for _, _, data in edges]

    nx.draw_networkx_edges(G, pos, edgelist=[(u,v) for u,v,d in edges],
                          width=widths, alpha=0.7,
                          edge_color='gray', arrows=True,
                          arrowsize=20, arrowstyle='->', ax=ax)

    # Add edge labels (flow and cost)
    edge_labels = {}
    for u, v, data in edges:
        if data['cost'] is not None:
            edge_labels[(u, v)] = f"{data['weight']:.0f} units\n(${data['cost']}/unit)"
        else:
            edge_labels[(u, v)] = f"{data['weight']:.0f} units"

    nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels,
                                font_size=9, ax=ax)

    # Add node labels
    nx.draw_networkx_labels(G, pos, font_size=12, font_weight='bold', ax=ax)

    # Add node annotations for capacity/demand
    if capacity is not None:
        for i, f in enumerate(factories):
            ax.annotate(f'Cap: {capacity[i]}',
                       xy=pos[f], xytext=(0, -30),
                       textcoords='offset points', ha='center',
                       bbox=dict(boxstyle='round,pad=0.3',
                                facecolor='yellow', alpha=0.3))

    if demand is not None:
        for i, c in enumerate(customers):
            ax.annotate(f'Dem: {demand[i]}',
                       xy=pos[c], xytext=(0, -30),
                       textcoords='offset points', ha='center',
                       bbox=dict(boxstyle='round,pad=0.3',
                                facecolor='orange', alpha=0.3))

    # Add title with total cost
    if total_cost is not None:
        plt.title(f'Transportation Network\nTotal Cost: ${total_cost:,.2f}',
                 fontsize=16, fontweight='bold')
    else:
        plt.title('Transportation Network', fontsize=16, fontweight='bold')

    # Add legend
    from matplotlib.lines import Line2D
    legend_elements = [
        Line2D([0], [0], marker='s', color='w', label='Factories',
               markerfacecolor='lightblue', markersize=15),
        Line2D([0], [0], marker='o', color='w', label='Customers',
               markerfacecolor='lightgreen', markersize=15),
        Line2D([0], [0], color='gray', lw=2, label='Shipments')
    ]
    ax.legend(handles=legend_elements, loc='upper left',
             bbox_to_anchor=(1.02, 1))

    plt.axis('off')
    plt.tight_layout()
    return fig, ax

def create_animated_visualization(flows, costs, capacity, demand):
    """
    Create multiple visualizations to compare scenarios
    """
    fig, axes = plt.subplots(1, 2, figsize=(15, 6))

    scenarios = [
        ('Optimal Solution', flows),
        ('Cost Matrix', costs)
    ]

    for idx, (title, data) in enumerate(scenarios):
        ax = axes[idx]
        G = nx.DiGraph()

        factories = ["F1", "F2"]
        customers = ["C1", "C2", "C3"]

        # Add nodes
        for f in factories:
            G.add_node(f, type='factory')
        for c in customers:
            G.add_node(c, type='customer')

        # Add edges
        if title == 'Optimal Solution':
            for i, f in enumerate(factories):
                for j, c in enumerate(customers):
                    if flows[i, j] > 0:
                        G.add_edge(f, c, weight=flows[i, j])
        else:
            for i, f in enumerate(factories):
                for j, c in enumerate(customers):
                    G.add_edge(f, c, weight=costs[i, j])

        pos = {}
        for i, f in enumerate(factories):
            pos[f] = (0, 1 - i/(len(factories)-1))
        for i, c in enumerate(customers):
            pos[c] = (1, 1 - i/(len(customers)-1))

        nx.draw(G, pos, with_labels=True, node_color=['lightblue', 'lightblue',
                                                      'lightgreen', 'lightgreen', 'lightgreen'],
               node_size=2000, font_weight='bold', ax=ax)

        labels = nx.get_edge_attributes(G, 'weight')
        nx.draw_networkx_edge_labels(G, pos, edge_labels=labels, ax=ax)

        ax.set_title(title)
        ax.axis('off')

    plt.tight_layout()
    return fig

# Main execution
if __name__ == "__main__":
    # Solve the transportation problem
    factories, customers, flows, capacity, demand, total_cost = solve_transportation_problem()

    # Create cost matrix
    cost = np.array([[4, 6, 9], [5, 4, 7]])

    # Create and visualize the network
    G, factories, customers = create_transportation_network(flows, cost)

    # Basic visualization
    fig1, ax1 = visualize_transportation_network(G, factories, customers,
                                                 capacity, demand, total_cost)
    plt.show()

    # Create comparison visualization
    fig2 = create_animated_visualization(flows, cost, capacity, demand)
    plt.show()

    # Print detailed results
    print("\n" + "="*50)
    print("TRANSPORTATION NETWORK DETAILS")
    print("="*50)
    print(f"Total Cost: ${total_cost:,.2f}")
    print("\nShipment Details:")
    for i, f in enumerate(factories):
        for j, c in enumerate(customers):
            if flows[i, j] > 0:
                print(f"{f} → {c}: {flows[i, j]:.0f} units @ ${cost[i, j]}/unit")

    # Calculate and display network metrics
    print("\n" + "="*50)
    print("NETWORK METRICS")
    print("="*50)

    # Calculate total flow
    total_flow = np.sum(flows)
    print(f"Total units shipped: {total_flow:.0f}")

    # Calculate utilization
    for i, f in enumerate(factories):
        shipped = np.sum(flows[i, :])
        util = (shipped / capacity[i]) * 100
        print(f"{f} utilization: {util:.1f}% ({shipped:.0f}/{capacity[i]} units)")

    # Check demand satisfaction
    for j, c in enumerate(customers):
        received = np.sum(flows[:, j])
        print(f"{c} demand: {received:.0f}/{demand[j]} units satisfied")
